// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJDxuN8fqeiML22RNDv6egSPNvqa106KY',
    appId: '1:414990451949:web:a45f275cb3905947f3b8e4',
    messagingSenderId: '414990451949',
    projectId: 'auth-b7952',
    authDomain: 'auth-b7952.firebaseapp.com',
    storageBucket: 'auth-b7952.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuAycVY9tO0OZBrbx5FFrmLnFwCxUlrM',
    appId: '1:414990451949:android:9f9cea59b10367d6f3b8e4',
    messagingSenderId: '414990451949',
    projectId: 'auth-b7952',
    storageBucket: 'auth-b7952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtmKv389bc55BnTh3Gjq2GuNso1Lsj83c',
    appId: '1:414990451949:ios:441735b434497d4ef3b8e4',
    messagingSenderId: '414990451949',
    projectId: 'auth-b7952',
    storageBucket: 'auth-b7952.appspot.com',
    iosBundleId: 'com.example.authfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtmKv389bc55BnTh3Gjq2GuNso1Lsj83c',
    appId: '1:414990451949:ios:441735b434497d4ef3b8e4',
    messagingSenderId: '414990451949',
    projectId: 'auth-b7952',
    storageBucket: 'auth-b7952.appspot.com',
    iosBundleId: 'com.example.authfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJDxuN8fqeiML22RNDv6egSPNvqa106KY',
    appId: '1:414990451949:web:ea1f3c6a6217970ff3b8e4',
    messagingSenderId: '414990451949',
    projectId: 'auth-b7952',
    authDomain: 'auth-b7952.firebaseapp.com',
    storageBucket: 'auth-b7952.appspot.com',
  );
}
